Support read_ahead_kb and max_ratio configs through mount options.

diff --git a/cmd/csi_driver/Dockerfile b/cmd/csi_driver/Dockerfile
--- a/cmd/csi_driver/Dockerfile
+++ b/cmd/csi_driver/Dockerfile
@@ -49,6 +49,10 @@ FROM distroless-$TARGETARCH AS output-image
 # Copy the mount/umount binaries
 COPY --from=debian /bin/mount /bin/mount
 COPY --from=debian /bin/umount /bin/umount
+COPY --from=debian /bin/mountpoint /bin/mountpoint
+# We should try to remove these
+COPY --from=debian /bin/sh /bin/sh
+COPY --from=debian /bin/cat /bin/cat
 
 # Copy shared libraries into distroless base.
 COPY --from=debian ${LD_LINUX_FILE} ${LIB_DIR}
@@ -68,6 +72,7 @@ COPY --from=debian /usr/bin/ldd /usr/bin/ldd
 SHELL ["/bin/bash", "-c"]
 RUN if ldd /bin/mount | grep "not found"; then echo "!!! Missing deps for mount command !!!" && exit 1; fi
 RUN if ldd /bin/umount | grep "not found"; then echo "!!! Missing deps for umount command !!!" && exit 1; fi
+RUN if ldd /bin/mountpoint | grep "not found"; then echo "!!! Missing deps for mountpoint command !!!" && exit 1; fi
 
 # Final build stage, create the real Docker image with ENTRYPOINT
 FROM output-image
